# Generated by Django 4.1.3 on 2022-11-18 15:08

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='state',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
