# Generated by Django 4.1.3 on 2022-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_pics'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
