# Generated by Django 4.1.3 on 2022-11-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_remove_productinstance_image_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='sold',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
