# Generated by Django 4.0.3 on 2022-03-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_category_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
