# Generated by Django 4.1.3 on 2022-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_productinstance_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True, verbose_name='address_line_1'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address_line_2'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='phone_number',
            field=models.CharField(max_length=255, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='zip_code',
            field=models.CharField(max_length=255, null=True, verbose_name='zip_code'),
        ),
    ]
