# Generated by Django 4.1.3 on 2022-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_remove_productinstance_sold_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_cart',
            field=models.IntegerField(blank=True, help_text='Leave this field blank', null=True),
        ),
    ]
