# Generated by Django 4.1.3 on 2022-11-14 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0004_product_quantity_in_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(max_length=255, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
            ],
            options={
                'ordering': ['city', 'state', 'first_name'],
            },
        ),
    ]
