# Generated by Django 4.1.3 on 2022-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_personaldetailstranslation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
