# Generated by Django 4.1.3 on 2022-11-14 13:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('showcase', '0005_personaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='state', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
