# Generated by Django 4.1.3 on 2022-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_alter_personaldetails_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
