# Generated by Django 4.1.3 on 2022-11-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_personaldetails_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter a product category (e.g TV, Fans)', max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True, verbose_name='address_line_1'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address_line_2'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone_number',
            field=models.CharField(max_length=255, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='discount_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_cart',
            field=models.IntegerField(blank=True, help_text='Leave this field blank', null=True, verbose_name='quantity_in_cart'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('m', 'Maintenance'), ('s', 'Sold'), ('r', 'Reserved')], default='a', help_text='Product availability', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Enter a product category (e.g LG, Samsung)', max_length=250, verbose_name='name'),
        ),
    ]
