# Generated by Django 4.1.3 on 2022-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_alter_personaldetails_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstancetranslation',
            name='status',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('m', 'Maintenance'), ('s', 'Sold'), ('r', 'Reserved')], default='a', help_text='Product availability', max_length=1, verbose_name='status'),
        ),
    ]
