# Generated by Django 4.1.3 on 2022-11-16 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showcase', '0013_remove_productinstancetranslation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailstranslation',
            name='buyer',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='buyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductInstanceTranslation',
        ),
    ]
